"""
Pydantic models for AI-generated voice escalation packages.
"""

from pydantic import BaseModel, Field
from typing import List


class VoiceOption(BaseModel):
    """
    Represents one possible decision option.
    """

    id: int = Field(..., description="Option number")
    title: str = Field(..., description="Option title")
    risk: str = Field(..., description="Risk of selecting this option")


class VoicePackage(BaseModel):
    """
    Structured response generated by OpenAI.
    """

    summary: str = Field(
        ...,
        description="Simple explanation of the situation."
    )

    business_risk: str = Field(
        ...,
        description="Business impact written in non-technical language."
    )

    priority_reason: str = Field(
        ...,
        description="Why this decision is important."
    )

    options: List[VoiceOption]

    expected_reply: str = Field(
        ...,
        description="Expected spoken reply from the user."
    )

    voice_script: str = Field(
        ...,
        description="Natural phone call script."
    )